// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetGest.Infrastructure.Persistence;

#nullable disable

namespace VetGest.Infrastructure.Migrations
{
    [DbContext(typeof(VetGestDbContext))]
    [Migration("20260904195913_AddDiaryEntryUniqueDailyIndex")]
    partial class AddDiaryEntryUniqueDailyIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("VetGest.Domain.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Normal");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Species", "Name")
                        .IsUnique();

                    b.HasIndex("Species", "Severity");

                    b.ToTable("AlertRules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333311"),
                            Conditions = "{\"temperature_min\": 39.5, \"temperature_max\": 40.5}",
                            Description = "Mother's temperature is elevated, which may indicate infection or stress.",
                            IsActive = true,
                            Name = "High Temperature",
                            Severity = "Attention",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333312"),
                            Conditions = "{\"temperature_min\": 40.5}",
                            Description = "Mother's temperature is dangerously high. Seek veterinary care immediately.",
                            IsActive = true,
                            Name = "Very High Temperature",
                            Severity = "Emergency",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333313"),
                            Conditions = "{\"temperature_max\": 37.5}",
                            Description = "Mother's temperature is below normal, which may indicate illness or stress.",
                            IsActive = true,
                            Name = "Low Temperature",
                            Severity = "Attention",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333314"),
                            Conditions = "{\"appetite\": \"decreased\"}",
                            Description = "Mother shows reduced interest in food, which may be normal near birth but needs monitoring.",
                            IsActive = true,
                            Name = "Decreased Appetite",
                            Severity = "Attention",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333315"),
                            Conditions = "{\"appetite\": \"none\"}",
                            Description = "Mother refuses all food. Consult a veterinarian if this persists.",
                            IsActive = true,
                            Name = "No Food Intake",
                            Severity = "Emergency",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333316"),
                            Conditions = "discharge,bleeding",
                            Description = "Abnormal discharge may indicate infection or complications. Seek immediate veterinary care.",
                            IsActive = true,
                            Name = "Abnormal Discharge",
                            Severity = "Emergency",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333317"),
                            Conditions = "lethargy,unresponsive",
                            Description = "Mother is unusually inactive or unresponsive. This requires immediate veterinary evaluation.",
                            IsActive = true,
                            Name = "Severe Lethargy",
                            Severity = "Emergency",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333321"),
                            Conditions = "{\"temperature_min\": 39.0, \"temperature_max\": 39.8}",
                            Description = "Mother's temperature is elevated, which may indicate infection or stress.",
                            IsActive = true,
                            Name = "High Temperature",
                            Severity = "Attention",
                            Species = "Cat"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333322"),
                            Conditions = "{\"temperature_min\": 39.8}",
                            Description = "Mother's temperature is dangerously high. Seek veterinary care immediately.",
                            IsActive = true,
                            Name = "Very High Temperature",
                            Severity = "Emergency",
                            Species = "Cat"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333323"),
                            Conditions = "{\"temperature_max\": 37.5}",
                            Description = "Mother's temperature is below normal, which may indicate illness or stress.",
                            IsActive = true,
                            Name = "Low Temperature",
                            Severity = "Attention",
                            Species = "Cat"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333324"),
                            Conditions = "{\"appetite\": \"decreased\"}",
                            Description = "Mother shows reduced interest in food, which may be normal near birth but needs monitoring.",
                            IsActive = true,
                            Name = "Decreased Appetite",
                            Severity = "Attention",
                            Species = "Cat"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333325"),
                            Conditions = "discharge,bleeding",
                            Description = "Abnormal discharge may indicate infection or complications. Seek immediate veterinary care.",
                            IsActive = true,
                            Name = "Abnormal Discharge",
                            Severity = "Emergency",
                            Species = "Cat"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333326"),
                            Conditions = "lethargy,unresponsive",
                            Description = "Mother is unusually inactive or unresponsive. This requires immediate veterinary evaluation.",
                            IsActive = true,
                            Name = "Severe Lethargy",
                            Severity = "Emergency",
                            Species = "Cat"
                        });
                });

            modelBuilder.Entity("VetGest.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("CurrentWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "IsActive");

                    b.ToTable("Pets", (string)null);
                });

            modelBuilder.Entity("VetGest.Domain.Entities.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EndDayGestation")
                        .HasColumnType("int");

                    b.Property<string>("FetalDevelopmentContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MaternalChangesContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("StartDayGestation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Species", "StartDayGestation", "EndDayGestation");

                    b.ToTable("Phases", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Fertilization and early embryo development",
                            EndDayGestation = 14,
                            FetalDevelopmentContent = "Embryos are microscopic. Cell division begins and implantation occurs.",
                            MaternalChangesContent = "Mother shows minimal physical changes. Appetite and behavior may remain normal.",
                            Name = "Initial",
                            Species = "Dog",
                            StartDayGestation = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Description = "Organogenesis and organ formation",
                            EndDayGestation = 29,
                            FetalDevelopmentContent = "Organs and body systems begin forming. Fetuses grow rapidly.",
                            MaternalChangesContent = "Mother may experience morning sickness, increased appetite, or mood changes.",
                            Name = "Intermediate",
                            Species = "Dog",
                            StartDayGestation = 15
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Description = "Bone mineralization and maternal demand increase",
                            EndDayGestation = 45,
                            FetalDevelopmentContent = "Fetuses develop bones, teeth, and hair. Significant size increase.",
                            MaternalChangesContent = "Mother's abdomen visibly enlarges. Appetite and water intake increase significantly.",
                            Name = "Growth",
                            Species = "Dog",
                            StartDayGestation = 30
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Description = "Final maturation and pre-birth preparation",
                            EndDayGestation = 62,
                            FetalDevelopmentContent = "Fetuses are now viable. Lungs mature and position for birth.",
                            MaternalChangesContent = "Mother seeks nesting materials, displays restlessness, and may refuse food near due date.",
                            Name = "Final",
                            Species = "Dog",
                            StartDayGestation = 46
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            Description = "Labor and delivery",
                            EndDayGestation = 70,
                            FetalDevelopmentContent = "Fetuses are fully developed and ready for birth.",
                            MaternalChangesContent = "Mother shows clear labor signs: contractions, nesting behavior, and discharge.",
                            Name = "Birth",
                            Species = "Dog",
                            StartDayGestation = 63
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222211"),
                            Description = "Fertilization and early embryo development",
                            EndDayGestation = 14,
                            FetalDevelopmentContent = "Embryos are microscopic. Implantation occurs in the uterine wall.",
                            MaternalChangesContent = "Mother may show subtle behavioral changes or temporarily hide.",
                            Name = "Initial",
                            Species = "Cat",
                            StartDayGestation = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222212"),
                            Description = "Organogenesis and major organ formation",
                            EndDayGestation = 30,
                            FetalDevelopmentContent = "Organs develop rapidly. Embryos become recognizable kittens.",
                            MaternalChangesContent = "Mother exhibits nesting behavior and may seek more attention.",
                            Name = "Intermediate",
                            Species = "Cat",
                            StartDayGestation = 15
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222213"),
                            Description = "Fetal growth and bone formation",
                            EndDayGestation = 48,
                            FetalDevelopmentContent = "Rapid growth phase. Kittens develop their characteristic features.",
                            MaternalChangesContent = "Mother's sides widen. May display increased vocalization and restlessness.",
                            Name = "Growth",
                            Species = "Cat",
                            StartDayGestation = 31
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222214"),
                            Description = "Final maturation and birth preparation",
                            EndDayGestation = 64,
                            FetalDevelopmentContent = "Kittens fully formed and viable. Fine-tuning of body systems.",
                            MaternalChangesContent = "Mother seeks secure nesting spaces and may stop eating days before labor.",
                            Name = "Final",
                            Species = "Cat",
                            StartDayGestation = 49
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222215"),
                            Description = "Labor and delivery",
                            EndDayGestation = 72,
                            FetalDevelopmentContent = "Kittens are fully developed and ready to be born.",
                            MaternalChangesContent = "Clear labor signs: panting, purring, tail twitching, and abdominal straining.",
                            Name = "Birth",
                            Species = "Cat",
                            StartDayGestation = 65
                        });
                });

            modelBuilder.Entity("VetGest.Domain.Entities.Pregnancy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CurrentPhaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EstimatedDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MatingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("OvulationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPhaseId");

                    b.HasIndex("EstimatedDueDate");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PetId");

                    b.HasIndex("Status");

                    b.HasIndex("PetId", "Status");

                    b.ToTable("Pregnancies", (string)null);
                });

            modelBuilder.Entity("VetGest.Domain.Entities.PregnancyDiaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Appetite")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Behavior")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhotoUrls")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PregnancyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SymptomsList")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EntryDate");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PregnancyId");

                    b.HasIndex("Temperature");

                    b.HasIndex("PregnancyId", "EntryDate")
                        .IsUnique();

                    b.ToTable("PregnancyDiaryEntries", (string)null);
                });

            modelBuilder.Entity("VetGest.Domain.Entities.VetConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InvitationExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PregnancyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TutorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("VetUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("InvitationCode")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("PregnancyId");

                    b.HasIndex("Status");

                    b.HasIndex("TutorUserId");

                    b.HasIndex("VetUserId");

                    b.HasIndex("PregnancyId", "Status");

                    b.HasIndex("VetUserId", "Status");

                    b.ToTable("VetConnections", (string)null);
                });

            modelBuilder.Entity("VetGest.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VetGest.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VetGest.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VetGest.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VetGest.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VetGest.Domain.Entities.Pregnancy", b =>
                {
                    b.HasOne("VetGest.Domain.Entities.Phase", "CurrentPhase")
                        .WithMany()
                        .HasForeignKey("CurrentPhaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VetGest.Domain.Entities.Pet", "Pet")
                        .WithMany("Pregnancies")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentPhase");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("VetGest.Domain.Entities.PregnancyDiaryEntry", b =>
                {
                    b.HasOne("VetGest.Domain.Entities.Pregnancy", "Pregnancy")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("PregnancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregnancy");
                });

            modelBuilder.Entity("VetGest.Domain.Entities.VetConnection", b =>
                {
                    b.HasOne("VetGest.Domain.Entities.Pregnancy", "Pregnancy")
                        .WithMany("VetConnections")
                        .HasForeignKey("PregnancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregnancy");
                });

            modelBuilder.Entity("VetGest.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Pregnancies");
                });

            modelBuilder.Entity("VetGest.Domain.Entities.Pregnancy", b =>
                {
                    b.Navigation("DiaryEntries");

                    b.Navigation("VetConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
